### ISSUE TITLE
Support HTML anchor tags without JavaScript

### ISSUE THREAD

**Issue by digitalcircuit** [ircv3/ircv3.github.io#209]
## In brief
* Use a different plugin to provide anchors to the IRCv3 website
  * Not everyone has JavaScript - Chrome on 2G, NoScript, text-based browsers, etc

## Test case
Visit https://ircv3.net/irc/#v3-2-metadata without JavaScript enabled, as referenced by [the IRCCloud blog](https://blog.irccloud.com/avatars/).

*More can be added later if needed, this is just to keep the issue from being forgotten.*

**Comment by DanielOaks** [comment]
Given that we use Netlify now, someone could conceivably write up a Jekyll plugin that handled this in the site compilation step rather than doing the JS. I consider this a pretty low-priority issue with the other stuff on the plate though, so contributions would be appreciated if anyone's interested!

**Comment by DanielOaks** [comment]
3568089c73b52fac4b17b91282983b14f16e6d1c should do this now
