### ISSUE TITLE
An overview for humans

### ISSUE THREAD

**Issue by techtonik** [ircv3/ircv3.github.io#9]
The site is all about specifications. Is there a plan to make information for humans - why new protocol, what issues need to be addressed, what are those shiny `exciting, useful new features for networks, and client / server authors` that `stakeholders in the IRC protocol, such as IRC networks and IRC network operators` interested in?

(reposted)

**Comment by Mikaela** [comment]
Related:
* original post: https://github.com/ircv3/ircv3-specifications/issues/154
* https://github.com/ircv3/ircv3.github.io/issues/8
* https://github.com/ircv3/ircv3.github.io/issues/7

**Comment by DanielOaks** [comment]
It's definitely a good idea, try to show off what's good about IRCv3 and why networks and software authors should care. I'll experiment, see what sort of changes we could make to show this better. If you have any mockups, feel free to post them in here.

#7 is planned and I'll be implementing it soon, but it doesn't really fit in this issue.

Could you please also close that original issue in the main repo? We'll keep the work in here.

**Comment by techtonik** [comment]
Conservative people (or seasoned developer) usually ask the most straightforward question - "What's wrong with existing protocol?". Or don't ask - "Does it work? Yes? Don't touch it." =)

**Comment by dequis** [comment]
Writeup by @jwheare, pretty good starting point IMO: https://blog.irccloud.com/ircv3/

That post was linked in [HN][1] and [reddit][2] and the comment threads brought up several FAQs we should address, some of which are common, some less so. The HN one was posted later, and jwheare made a top level comment addressing some of the concerns that reddit had. Overall both threads seem nice and they don't go too deep into topics that don't concern us at all like discussing the technical merits/flaws of XMPP or whatever other protocol.

There are a few comments with expectations of ircv3 being a direct competitor (same feature set) to hipchat or slack. One of them said "The irc work group is in dire need of a serious product manager". I interpreted that one as "we should fix this ticket".

[1]: https://news.ycombinator.com/item?id=11005999
[2]: https://www.reddit.com/r/programming/comments/43emw6/ircv3_advance_the_irc_protocol/

**Comment by DanielOaks** [comment]
That sounds entirely fair. Right now it acts mostly as a signboard that says "Go look at these other things!" rather than actually bringing up and addressing *why* people should be looking at them and IRCv3 as a whole.

That blog is a good thing to keep in mind, but it also comes down to the best way to present our front page and the WG as a whole. I'd be aiming more for a clean overview on the front page than just posting something like @jwheare's post right there.

I'll do some experimenting and throw some ideas at the wall for the front page and others that address those other sort of issues.

**Comment by techtonik** [comment]
I read specs name and short description a bit and must say that while all this stuff is very useful for a technical user (thanks to details) it lacks the user-centric view. As a user, I need a limited information (preferrably with screenshots) about communication features that I can immediately understand and only then I may want to expand it into the implementation/protocol details.

So, for example, I need the simplicity of running a web-based IRC client on my 24/7 server (with backup option) so that I can login and check messages there. I also need it to send me notifications about amount of new messages to my phone. And I don't see how a new protocol helps me there. It would help if communication was done over HTTPS.

**Comment by DanielOaks** [comment]
Yep, that's the plan @techtonik. I've expanded on the larger plans in #64, and this will be one part of that.

**Comment by DanielOaks** [comment]
Alright, bit of an update. The first part of this should come with the new [landing page](http://ircv3.net/), particularly the section listing IRCv3 features in a more user-centric way. The other primary part should come along with #82 while we do the redesign of that page.

I could imagine perhaps a features page which lists explicit features for different classes of users and developers at some point in the future or something roughly like that, but I'd like to get the base of the site updated to better suite people in general before we go about creating specific new pages for it, since it's something we should be doing in general anyways.

**Comment by techtonik** [comment]
> features page which lists explicit features for different classes of users and developers at some point in the future

That would be an improvement. And it would be nice to have some "progressive enhancement" content - starting with simple tutorials, like building and IRC client in 15 minutes. I hope the spec stays simple for that entry level?

**Comment by DanielOaks** [comment]
I think it's important to make sure we have that info on the relevant existing sections of the site first before we make a page like that, but it is in the cards.

I'm not sure how appropriate that tutorials idea is for the IRCv3 site itself, but it's definitely an interesting idea. Most of the specs on here are intended for people already reasonably familiar with the client protocol (the basic terms at least), or at least able to look up info on it from other sources, rather than as a teaching resource.

**Comment by techtonik** [comment]
For me the primary audience of this resource are people who are learning to code and dreaming of building their own alternative to facebook messaging, based on open protocols and interoperability.

**Comment by DanielOaks** [comment]
I think we can consider this done in terms of the home and WG pages, next lot of work for this is in the primary spec page itself, can go into the #82 work
